### ISSUE TITLE
Creating a GraphDB repo with SHACL validation via config.ttl do not work in preload

### ISSUE THREAD

**Issue by vemonet** [Ontotext-AD/graphdb-docker#17]
1. I created a repository with SHACL validation enabled using the web UI
2. I went to the GraphDB Home directory, in the repository I created and took the `config.ttl` that has been generated

```turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sail: <http://www.openrdf.org/config/sail#> .
@prefix sail-shacl: <http://rdf4j.org/config/sail/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<#cohd> a rep:Repository;
  rep:repositoryID "cohd";
  rep:repositoryImpl [
      rep:repositoryType "graphdb:FreeSailRepository";
      <http://www.openrdf.org/config/repository/sail#sailImpl> [
          sail-shacl:cacheSelectNodes true;
          sail-shacl:globalLogValidationExecution false;
          sail-shacl:ignoreNoShapesLoadedException false;
          sail-shacl:logValidationPlans false;
          sail-shacl:logValidationViolations false;
          sail-shacl:parallelValidation true;
          sail-shacl:performanceLogging false;
          sail-shacl:rdfsSubClassReasoning true;
          sail-shacl:serializableValidation true;
          sail-shacl:undefinedTargetValidatesAllSubjects false;
          sail-shacl:validationEnabled true;
          sail:delegate [
              <http://www.ontotext.com/trree/owlim#base-URL> "https://w3id.org/cohd/";
              <http://www.ontotext.com/trree/owlim#check-for-inconsistencies> "false";
              <http://www.ontotext.com/trree/owlim#defaultNS> "";
              <http://www.ontotext.com/trree/owlim#disable-sameAs> "true";
              <http://www.ontotext.com/trree/owlim#enable-context-index> "true";
              <http://www.ontotext.com/trree/owlim#enable-literal-index> "true";
              <http://www.ontotext.com/trree/owlim#enablePredicateList> "true";
              <http://www.ontotext.com/trree/owlim#entity-id-size> "40";
              <http://www.ontotext.com/trree/owlim#entity-index-size> "999999999";
              <http://www.ontotext.com/trree/owlim#imports> "";
              <http://www.ontotext.com/trree/owlim#in-memory-literal-properties> "true";
              <http://www.ontotext.com/trree/owlim#query-limit-results> "0";
              <http://www.ontotext.com/trree/owlim#query-timeout> "0";
              <http://www.ontotext.com/trree/owlim#read-only> "false";
              <http://www.ontotext.com/trree/owlim#repository-type> "file-repository";
              <http://www.ontotext.com/trree/owlim#ruleset> "empty";
              <http://www.ontotext.com/trree/owlim#storage-folder> "storage";
              <http://www.ontotext.com/trree/owlim#throw-QueryEvaluationException-on-timeout> "false";
              sail:sailType "graphdb:FreeSail"
            ];
          sail:sailType "graphdb:ShaclSail"
        ]
    ];
  rdfs:label "COHD" .
```

3. I now try to run graphdb-preload using this `config.ttl` file (which should be valid since it has been generated by GraphDB itself) 

But I get this error:

```
graphdb-preload    | 12:58:32.985 [main] INFO com.ontotext.config.AbstractParameter - Configured parameter 'do.resolve.entities' to default value 'true'
graphdb-preload    | 12:58:32.985 [main] INFO com.ontotext.config.AbstractParameter - Configured parameter 'do.load.data' to default value 'true'
graphdb-preload    | 12:58:32.985 [main] INFO com.ontotext.rio.parallel.ParallelLoader - Data will be parsed + resolved + loaded.
graphdb-preload    | 12:58:32.985 [main] INFO com.ontotext.config.AbstractParameter - Configured parameter 'graphdb.persistent.parallel.inferencers' to default value 'false'
graphdb-preload    | 12:58:33.020 [main] INFO org.eclipse.rdf4j.sail.shacl.ShaclSail - Shapes will be persisted in: /opt/graphdb/home/data/repositories/cohd/shapes-graph/
graphdb-preload    | Exception in thread "main" java.lang.IllegalStateException: Only graphdb repositories are supported
graphdb-preload    | 	at com.ontotext.graphdb.loadrdf.BaseLoadTool.getSail(BaseLoadTool.java:153)
graphdb-preload    | 	at com.ontotext.graphdb.loadrdf.BaseLoadTool.createRepositoryInSystemLocation(BaseLoadTool.java:231)
graphdb-preload    | 	at com.ontotext.graphdb.loadrdf.BaseLoadTool.mainInternal(BaseLoadTool.java:132)
graphdb-preload    | 	at com.ontotext.graphdb.loadrdf.PreloadData.main(PreloadData.java:2175)
```

The error seems to indicate GraphDB  does not recognize the type provided, but not sure which one it is, but it has been generated by GraphDB itself so really no idea 

Note that this is working when using a previous "config.ttl" without SHACL validation enabled.

It is quite strange that GraphDB fails to read the file it generates

On GraphDB Free 9.3.0

**Comment by nikolaykolev** [comment]
seems to be working fine on more recent versions
